image: yapic-debian

before_script:
  - export LANG=C.UTF-8
  - PATH=${HOME}/.local/bin/:$PATH
  - cd /tmp
  - ~/.local/bin/virtualenv virtenv --system-site-packages
  - source virtenv/bin/activate
  - pip install -e ${CI_PROJECT_DIR}
  - cd ${CI_PROJECT_DIR}


stages:
  - test
  - deploy


run_cpu_tests:
  stage: test
  script:
    - pip install nose
    - cd ${CI_PROJECT_DIR}
    - nosetests --with-doctest --with-timer --with-coverage --cover-package=yapic_io
    - sleep 5

pages:
  stage: deploy
  script:
    - cd ${CI_PROJECT_DIR}/doc
    - sphinx-apidoc -o source ../yapic_io
    - pip freeze
    - make html
    # the next line requires this volume in /etc/gitlab-runner/config.toml: '/var/www/html/yapic:/public/:rw'
    - cp -R ${CI_PROJECT_DIR}/doc/build /public/
    - sleep 5
  artifacts:
    paths:
    - doc/build
  only:
  - master

