before_script:
  - export LANG=C.UTF-8
  - PATH=${HOME}/.local/bin/:$PATH

stages:
  - test
  - deploy


run_cpu_tests:
  image: python:3.6
  stage: test
  script:
    - pip install --upgrade pip
    - pip install Cython
    - pip install -e ${CI_PROJECT_DIR}
    - pip install nose
    - cd ${CI_PROJECT_DIR}
    - nosetests --with-doctest --with-coverage --cover-package=yapic_io
