before_script:
  - export LANG=C.UTF-8
  - PATH=${HOME}/.local/bin/:$PATH

stages:
  - test
  - deploy


install:
  image: yapic-nopython
  stage: test
  script:
    - pip install Cython
    - if [ ${RUN_NIGHTLY_BUILD} ]; then pip install ${CI_PROJECT_DIR}; fi


run_cpu_tests:
  image: yapic-python
  stage: test
  script:
    - pip install Cython
    - pip install -e ${CI_PROJECT_DIR}
    - pip install nose
    - cd ${CI_PROJECT_DIR}
    - nosetests --with-doctest --with-timer --with-coverage --cover-package=yapic_io


trigger_yapic_cli:
  image: yapic-python
  stage: deploy
  script:
    - curl -X POST -F token=2d3b6e8a9681ea863cf90e6ec5d021 -F ref=master http://animate-x3.dzne.ds/api/v4/projects/12/trigger/pipeline

docs:
  image: yapic-python
  stage: deploy
  script:
    - pip install Cython
    - pip install -e ${CI_PROJECT_DIR}
    - pip install -r requirements_doc.txt
    - cd ${CI_PROJECT_DIR}/doc
    - sphinx-apidoc -o source ../yapic_io
    - pip freeze
    - make html
    # the next line requires this volume in /etc/gitlab-runner/config.toml: '/var/www/html/yapic:/public/ml/:rw'
    - cp -R ${CI_PROJECT_DIR}/doc/build /public/io/
  artifacts:
    paths:
    - doc/build
  only:
  - master
