before_script:
  - export LANG=C.UTF-8
  - PATH=${HOME}/.local/bin/:$PATH

stages:
  - test
  - deploy


run_cpu_tests:
  image: python:3.6
  stage: test
  script:
    - pip install --upgrade pip
    - pip install Cython
    - pip install -e ${CI_PROJECT_DIR}
    - pip install nose
    - cd ${CI_PROJECT_DIR}
    - nosetests --with-doctest --with-coverage --cover-package=yapic_io


docs:
  image: python:3.6
  stage: deploy
  script:
    - pip install --upgrade pip
    - pip install Cython
    - pip install -e ${CI_PROJECT_DIR}
    - pip install -r requirements_doc.txt
    - cd ${CI_PROJECT_DIR}/doc
    - sphinx-apidoc -o source ../yapic_io
    - pip freeze
    - make html
    # the next line requires this volume in /etc/gitlab-runner/config.toml: '/var/www/html/yapic:/public/ml/:rw'
    - cp -R ${CI_PROJECT_DIR}/doc/build /public/io/
  artifacts:
    paths:
    - doc/build
  only:
  - master
